### ISSUE TITLE
Student login with email

### ISSUE THREAD

**Issue by justin-prabhakaran** [justin-prabhakaran/classroom-spring#8]
Student login with email is needs to be done 
1. update repo
2. update datasource
3. update usecase (dont create new)

**Comment by justin-prabhakaran** [comment]
assigned to @karthikeyan-csdev

**Comment by karthikeyan-csdev** [comment]
authentication implemented for student email and password https://github.com/justin-prabhakaran/classroom-spring/commit/77bf18a71e18d8eb20db8e8a85c08045a3bc6cd6

**Comment by justin-prabhakaran** [comment]
resolved in #9
